In [1]:
import logging,sys
from argparse import ArgumentParser
logging.basicConfig(format="[ %(levelname)s ] %(message)s", level=logging.INFO, stream=sys.stdout)
log = logging.getLogger()

In [ ]:
f = open('temp1.txt', 'w')
for i in range(1, 416):
    f.writelines('    ' + 'slice_point:' + str(i) + '\t\n')
f.close()

In [ ]:
f = open('temp0.txt', 'w')
for i in range(416):
    f.writelines('  ' + 'top:"data_ods_' + str(i) + '"\t\n')
f.close()

In [ ]:
f = open('temp.txt', 'w')
for i in range(0, 416, 2):
    f.writelines('    ' + 'bottom:"data_ods_' + str(i) + '"\t\n')
f.close()

In [ ]:
f = open('temp2.txt', 'w')
for i in range(1, 416, 2):
    f.writelines('    ' + 'bottom:"data_even_' + str(i) + '"\t\n')
f.close()

In [2]:
caffe_root = '/data/ssd-caffe/new-yolov3-caffe'
img_file = '/data/github_repos/yolov3-tiny-fit-ncs/ncs/standard_size_416_persons.jpg'
prototxt = '/media/yyp/DATA/Hi3519AV100/test_model_yyp/test.prototxt'
import sys, os
sys.path.insert(0, caffe_root + '/python/')
import caffe
import matplotlib.pyplot as plt
%matplotlib inline
caffe.set_mode_cpu()
net = caffe.Net(prototxt,caffe.TEST)
img_caffe_io = caffe.io.load_image(img_file)
#print(img.shape)
#plt.imshow(img)
import cv2
import numpy as np
cv2.__version__
img = cv2.imread(img_file) ###BGR
resized_img = cv2.resize(img, (416,416))
resized_img = cv2.cvtColor(resized_img, cv2.COLOR_BGR2RGB) # cv2默认为bgr顺序
img_ = np.transpose(resized_img, (2, 0, 1))
print(img_.shape)
#print(img_)
normerlized_img = img_/255.0
#normerlized_img = img_
print(normerlized_img)

net.blobs['data'].data[...] = normerlized_img

output = net.forward()
for k, v in output.items():
    print(k)
    print(v.shape)
    print(v)
#net = caffe.Net(prototxt,caffe.TRAIN)
net.save("test.caffemodel")


/usr/local/lib/python3.5/dist-packages/skimage/io/_io.py:48: UserWarning: `as_grey` has been deprecated in favor of `as_gray`
  warn('`as_grey` has been deprecated in favor of `as_gray`')


(3, 416, 416)
[[[0.04313725 0.05490196 0.05490196 ... 0.05490196 0.09019608 0.02745098]
  [0.05490196 0.03921569 0.12941176 ... 0.16470588 0.16862745 0.15294118]
  [0.03529412 0.05882353 0.3372549  ... 0.12156863 0.18431373 0.2       ]
  ...
  [0.21568627 0.21568627 0.21960784 ... 0.40784314 0.41176471 0.4       ]
  [0.21960784 0.21960784 0.22352941 ... 0.41176471 0.41568627 0.4       ]
  [0.20392157 0.20784314 0.21176471 ... 0.40392157 0.41568627 0.42352941]]

 [[0.09411765 0.09411765 0.07058824 ... 0.26666667 0.23921569 0.14509804]
  [0.10196078 0.0745098  0.14117647 ... 0.36078431 0.32156863 0.28235294]
  [0.07843137 0.09019608 0.35686275 ... 0.2745098  0.34509804 0.36078431]
  ...
  [0.23137255 0.23137255 0.23529412 ... 0.42352941 0.42745098 0.41568627]
  [0.23529412 0.23529412 0.23921569 ... 0.42745098 0.43137255 0.41568627]
  [0.21960784 0.22352941 0.22745098 ... 0.41960784 0.43137255 0.43921569]]

 [[0.         0.         0.01568627 ... 0.31372549 0.31372549 0.23921569]
  [0.015

In [ ]:
caffemodel = "test.caffemodel"
net = caffe.Net(prototxt, caffemodel, caffe.TEST)
#show the params
k_v_s = [(k, v) for k, v in net.params.items()]
key_vecnums = [(vecs[0], len(vecs[1])) for vecs in k_v_s]
[(vecs[0], [(vecs[1][i].data.shape, vecs[1][i].data) for i in range(len(vecs[1]))])for vecs in k_v_s]

In [ ]:
net.blobs['data'].data[...] = normerlized_img
output = net.forward()
for k, v in output.items():
    print(k)
    print(v.shape)
    print(v)

In [ ]:
[(k, v.data.shape, v.data) for k, v in net.blobs.items() if v.data.shape[3] !=1 and v.data.shape[2] !=1 ]

In [ ]:
caffe_root = '/data/ssd-caffe/new-yolov3-caffe'
img_file = '/data/github_repos/yolov3-tiny-fit-ncs/ncs/standard_size_416_persons.jpg'
prototxt = '/data/NCS/OpenVINO/tensorflow-yolo-v3/model_optimizer/20190218182235_TinyYoloV3NCS.prototxt'
caffemodel = '/data/NCS/OpenVINO/tensorflow-yolo-v3/model_optimizer/20190218182235_TinyYoloV3NCS.caffemodel'

import sys, os
sys.path.insert(0, caffe_root + '/python')
import caffe
import matplotlib.pyplot as plt
%matplotlib inline
caffe.set_mode_cpu()
net = caffe.Net(prototxt, caffemodel, caffe.TEST)
img_caffe_io = caffe.io.load_image(img_file)
#print(img.shape)
#plt.imshow(img)
import cv2
import numpy as np
cv2.__version__
img = cv2.imread(img_file) ###BGR
resized_img = cv2.resize(img, (416,416))
resized_img = cv2.cvtColor(resized_img, cv2.COLOR_BGR2RGB) # cv2默认为bgr顺序
img_ = np.transpose(resized_img, (2, 0, 1))
print(img_.shape)
#print(img_)
normerlized_img = img_/255.0
#normerlized_img = img_
#print(normerlized_img)

net.blobs['data'].data[...] = normerlized_img
inputData = net.blobs['data'].data[...]
#inputData

In [ ]:
outputs = net.forward()
print(outputs)

In [ ]:
#plt.imshow(transformer.deprocess('data', inputData[0]))
#[(k, v.data.shape, v.data) for k, v in net.blobs.items()]

In [ ]:
#show the params
#k_v_s = [(k, v) for k, v in net.params.items()]
#key_vecnums = [(vecs[0], len(vecs[1])) for vecs in k_v_s]
#[(vecs[0], [vecs[1][i].data.shape for i in range(len(vecs[1]))])for vecs in k_v_s]

In [ ]:
#key_vecnums = [(vecs[0], len(vecs[1])) for vecs in k_v_s]
#[(vecs[0], [vecs[1][i].data for i in range(len(vecs[1]))])for vecs in k_v_s]

In [ ]:
class YoloV3Params:
    # ------------------------------------------- Extracting layer parameters ------------------------------------------
    # Magic numbers are copied from yolo samples
    def __init__(self, param, side):
        self.num = 3 if 'num' not in param else len(param['mask'].split(',')) if 'mask' in param else int(param['num'])
        self.coords = 4 if 'coords' not in param else int(param['coords'])
        #self.classes = 80 if 'classes' not in param else int(param['classes'])
        self.classes = 6 if 'classes' not in param else int(param['classes'])
        #self.anchors = [10.0, 13.0, 16.0, 30.0, 33.0, 23.0, 30.0, 61.0, 62.0, 45.0, 59.0, 119.0, 116.0, 90.0, 156.0, 198.0,
                        #373.0, 326.0] if 'anchors' not in param else [float(a) for a in param['anchors'].split(',')]
        self.anchors = [10,25,  20,50,  30,75, 50,125,  80,200,  150,150] if 'anchors' not in param else [float(a) for a in param['anchors'].split(',')]
        self.side = side
        if self.side == 13:
            self.anchor_offset = 2 * 3
        elif self.side == 26:
            self.anchor_offset = 2 * 0
        elif self.side == 52:
            self.anchor_offset = 2 * 0
        else:
            assert False, "Invalid output size. Only 13, 26 and 52 sizes are supported for output spatial dimensions"

    def log_params(self):
        params_to_print = {'classes': self.classes, 'num': self.num, 'coords': self.coords, 'anchors': self.anchors}
        [log.info("         {:8}: {}".format(param_name, param)) for param_name, param in params_to_print.items()]


def entry_index(side, coord, classes, location, entry):
    side_power_2 = side ** 2
    n = location // side_power_2
    loc = location % side_power_2
    return int(side_power_2 * (n * (coord + classes + 1) + entry) + loc)


def scale_bbox(x, y, h, w, class_id, confidence, h_scale, w_scale):
    xmin = int((x - w / 2) * w_scale)
    ymin = int((y - h / 2) * h_scale)
    xmax = int(xmin + w * w_scale)
    ymax = int(ymin + h * h_scale)
    return dict(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, class_id=class_id, confidence=confidence)


def parse_yolo_region(blob, resized_image_shape, original_im_shape, params, threshold):
    # ------------------------------------------ Validating output parameters ------------------------------------------
    _, _, out_blob_h, out_blob_w = blob.shape
    assert out_blob_w == out_blob_h, "Invalid size of output blob. It sould be in NCHW layout and height should " \
                                     "be equal to width. Current height = {}, current width = {}" \
                                     "".format(out_blob_h, out_blob_w)

    # ------------------------------------------ Extracting layer parameters -------------------------------------------
    orig_im_h, orig_im_w = original_im_shape
    resized_image_h, resized_image_w = resized_image_shape
    objects = list()
    predictions = blob.flatten()
    side_square = params.side * params.side

    # ------------------------------------------- Parsing YOLO Region output -------------------------------------------
    for i in range(side_square):
        row = i // params.side
        col = i % params.side
        for n in range(params.num):
            obj_index = entry_index(params.side, params.coords, params.classes, n * side_square + i, params.coords)
            scale = predictions[obj_index]
            if scale < threshold:
                continue
            box_index = entry_index(params.side, params.coords, params.classes, n * side_square + i, 0)
            x = (col + predictions[box_index + 0 * side_square]) / params.side * resized_image_w
            y = (row + predictions[box_index + 1 * side_square]) / params.side * resized_image_h
            # Value for exp is very big number in some cases so following construction is using here
            try:
                w_exp = exp(predictions[box_index + 2 * side_square])
                h_exp = exp(predictions[box_index + 3 * side_square])
            except OverflowError:
                continue
            w = w_exp * params.anchors[params.anchor_offset + 2 * n]
            h = h_exp * params.anchors[params.anchor_offset + 2 * n + 1]
            for j in range(params.classes):
                class_index = entry_index(params.side, params.coords, params.classes, n * side_square + i,
                                          params.coords + 1 + j)
                confidence = scale * predictions[class_index]
                if confidence < threshold:
                    continue
                objects.append(scale_bbox(x=x, y=y, h=h, w=w, class_id=j, confidence=confidence,
                                          h_scale=orig_im_h / resized_image_h, w_scale=orig_im_w / resized_image_w))
    return objects


def intersection_over_union(box_1, box_2):
    width_of_overlap_area = min(box_1['xmax'], box_2['xmax']) - max(box_1['xmin'], box_2['xmin'])
    height_of_overlap_area = min(box_1['ymax'], box_2['ymax']) - max(box_1['ymin'], box_2['ymin'])
    if width_of_overlap_area < 0 or height_of_overlap_area < 0:
        area_of_overlap = 0
    else:
        area_of_overlap = width_of_overlap_area * height_of_overlap_area
    box_1_area = (box_1['ymax'] - box_1['ymin']) * (box_1['xmax'] - box_1['xmin'])
    box_2_area = (box_2['ymax'] - box_2['ymin']) * (box_2['xmax'] - box_2['xmin'])
    area_of_union = box_1_area + box_2_area - area_of_overlap
    if area_of_union == 0:
        return 0
    return area_of_overlap / area_of_union

def build_argparser():
    parser = ArgumentParser()
    parser.add_argument("-pt", "--prob_threshold", help="Probability threshold for detections filtering",
                        default=0.5, type=float)
    parser.add_argument("-iout", "--iou_threshold", help="Intersection over union threshold for overlapping detections"
                                                         " filtering", default=0.4, type=float)
    parser.add_argument("-ni", "--number_iter", help="Number of inference iterations", default=1, type=int)
    parser.add_argument("-pc", "--perf_counts", help="Report performance counters", default=False, action="store_true")
    return parser

In [ ]:
objects = list()
args = build_argparser().parse_args()
for layer_name, out_blob in outputs.items():
    print(layer_name)
    print(out_blob)
    #layer_params = YoloV3Params(net.layers[layer_name].params, out_blob.shape[2])
    layer_params = YoloV3Params('', out_blob.shape[2])

    log.info("Layer {} parameters: ".format(layer_name))
    layer_params.log_params()
    in_frame = inputData
    frame = in_frame
    objects += parse_yolo_region(out_blob, in_frame.shape[2:],
                                 frame.shape[:-1], layer_params,
                                 args.prob_threshold)

# Filtering overlapping boxes with respect to the --iou_threshold CLI parameter
for i in range(len(objects)):
    if objects[i]['confidence'] == 0:
        continue
    for j in range(i + 1, len(objects)):
        if intersection_over_union(objects[i], objects[j]) > args.iou_threshold:
            objects[j]['confidence'] = 0

# Drawing objects with respect to the --prob_threshold CLI parameter
objects = [obj for obj in objects if obj['confidence'] >= args.prob_threshold]

if len(objects):
    log.info("\nDetected boxes for batch {}:".format(1))
    log.info(" Class ID | Confidence | XMIN | YMIN | XMAX | YMAX | COLOR ")

origin_im_size = frame.shape[:-1]
for obj in objects:
    # Validation bbox of detected object
    if obj['xmax'] > origin_im_size[0] or obj['ymax'] > origin_im_size[0] or obj['xmin'] < 0 or obj['ymin'] < 0:
        continue
    color = (int(min(obj['class_id'] * 12.5, 255)),
             min(obj['class_id'] * 7, 255), min(obj['class_id'] * 5, 255))
    det_label = labels_map[obj['class_id']] if labels_map and len(labels_map) >= obj['class_id'] else \
        str(obj['class_id'])
    log.info("{:^9} | {:10f} | {:4} | {:4} | {:4} | {:4} | {} ".format(det_label, obj['confidence'], obj['xmin'],
                                                                       obj['ymin'], obj['xmax'], obj['ymax'],
                                                                       color))

    cv2.rectangle(frame, (obj['xmin'], obj['ymin']), (obj['xmax'], obj['ymax']), color, 2)
    cv2.putText(frame,
                "#" + det_label + ' ' + str(round(obj['confidence'] * 100, 1)) + ' %',
                (obj['xmin'], obj['ymin'] - 7), cv2.FONT_HERSHEY_COMPLEX, 0.6, color, 1)

# Draw performance stats over frame
inf_time_message = "Inference time: N\A for async mode" if is_async_mode else \
    "Inference time: {:.3f} ms".format(det_time * 1e3)
render_time_message = "OpenCV rendering time: {:.3f} ms".format(render_time * 1e3)
async_mode_message = "Async mode is on. Processing request {}".format(cur_request_id) if is_async_mode else \
    "Async mode is off. Processing request {}".format(cur_request_id)
parsing_message = "YOLO parsing time is {:.3f}".format(parsing_time * 1e3)

cv2.putText(frame, inf_time_message, (15, 15), cv2.FONT_HERSHEY_COMPLEX, 0.5, (200, 10, 10), 1)
cv2.putText(frame, render_time_message, (15, 45), cv2.FONT_HERSHEY_COMPLEX, 0.5, (10, 10, 200), 1)
cv2.putText(frame, async_mode_message, (10, int(origin_im_size[0] - 20)), cv2.FONT_HERSHEY_COMPLEX, 0.5,
            (10, 10, 200), 1)
cv2.putText(frame, parsing_message, (15, 30), cv2.FONT_HERSHEY_COMPLEX, 0.5, (10, 10, 200), 1)

start_time = time()
cv2.imshow("DetectionResults", frame)
render_time = time() - start_time

key = cv2.waitKey(0)
'''
# Tab key
if key == 27:
    break
# ESC key
if key == 9:
    break   
'''
cv2.destroyAllWindows()
del net